/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#4d2d00",
        "surface-container-low": "#131314",
        "on-primary-fixed-variant": "#512800",
        "inverse-surface": "#fcf8f9",
        "on-secondary": "#512f00",
        "on-surface": "#ffffff",
        "surface": "#0e0e0f",
        "secondary-fixed": "#ffc78a",
        "on-tertiary": "#665100",
        "on-background": "#ffffff",
        "secondary": "#ffa52a",
        "primary-fixed": "#fd8b00",
        "primary-fixed-dim": "#ea8000",
        "secondary-container": "#875200",
        "tertiary-fixed": "#ffd33a",
        "surface-container-lowest": "#000000",
        "on-primary": "#532a00",
        "tertiary": "#ffe393",
        "inverse-on-surface": "#555556",
        "surface-container": "#19191b",
        "on-primary-container": "#442100",
        "on-primary-fixed": "#180800",
        "on-secondary-container": "#fff6f0",
        "surface-variant": "#262627",
        "surface-bright": "#2c2c2d",
        "surface-container-highest": "#262627",
        "primary-container": "#fd8b00",
        "on-secondary-fixed-variant": "#744600",
        "tertiary-container": "#ffd33a",
        "on-error-container": "#ffd2c8",
        "outline": "#767576",
        "on-tertiary-fixed-variant": "#675200",
        "surface-dim": "#0e0e0f",
        "error-container": "#b92902",
        "inverse-primary": "#914d00",
        "primary-dim": "#ed8200",
        "secondary-dim": "#ef981a",
        "on-tertiary-fixed": "#453600",
        "on-surface-variant": "#acaaab",
        "error": "#ff7351",
        "on-error": "#450900",
        "primary": "#ff9f4a",
        "outline-variant": "#484849",
        "background": "#0e0e0f",
        "on-tertiary-container": "#5c4900",
        "tertiary-fixed-dim": "#efc52b",
        "error-dim": "#d53d18",
        "secondary-fixed-dim": "#ffb55c",
        "surface-tint": "#ff9f4a",
        "surface-container-high": "#1f1f21",
        "tertiary-dim": "#efc52b"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      fontFamily: {
        "headline": ["Lexend", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      }
    },
  },
  plugins: [],
}
